version: "3.7"

services:
  redis:
    image: redis:5.0
    ports:
      - 6379:6379
    volumes:
      - ./tmp/redis-data:/data

  postgres:
    image: postgres:11.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql