default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  password: password
  username: postgres
  database: cqrs_event_api_development

test:
  <<: *default
  host: localhost
  password: password
  username: postgres
  database: cqrs_event_api_test

production:
  <<: *default
  database: cqrs_event_api_production
  username: cqrs_event_api
  password: <%= ENV['CQRS_EVENT_API_DATABASE_PASSWORD'] %>
